### PR TITLE
Mapj4

### PR DESCRIPTION
**Pull request by SamanthaDawsonBanks**
subject to:
- code
- review
- bug fixes
- lack of comments
- about 30 TODOs
- at least 2 FIXMEs
- JDoc
- better unit testing
- my terrible maths
- penguin infestation

I "think" this is a working amalgamated gridded map

### CODE REVIEW

**Review by stevempope — APPROVED** [review]
Can I just say how pleased I am that the OMG step away from the code comment is gone!

On a more serious note, the code looks much closer to finished. Well done Dave

**Comment by stevempope** [comment]
The only thing I want to add to my review is I thought there was a new way for a dummy map in the unit testing, but I may simply not be remembering right!

**Comment by SamanthaDawsonBanks** [comment]
Not so much that the dummy map would be different just that the way to call it was different.

The omg was there from before the relative neighbour addition to the map design.
But yes it is a great feeling to clean up the code crud

**Comment by stevempope** [comment]
I see, thanks for clearing that up. Well done on getting this done.

**Comment by HarryWJackson1996** [comment]
that is really great, nice one getting it done!

**Pull request merged**
