### PR TITLE
dummy object that makes a static map DS of the sample map we use in

### PR DESCRIPTION
**Pull request by SamanthaDawsonBanks**
presentations - access as something like: dummyMap dm = new dummyMap();
"pathfind"(dm.m)

this **will not work** until i fix the map working on it now but when down will create a new DM object that holds a Map object with one LiDAR Layer and an amalgamated map

for testing, unit testing and example GUI

//TODO ext then with LReads for each colour as per presentation

### CODE REVIEW

**Comment by SamanthaDawsonBanks** [comment]
actually i'm going to rework the way this is built (so it is used differently) please still review code but do not merge

**Review by stevempope — CHANGES_REQUESTED** [review]
Requesting Changes to reflect the fact that you don't want this merged. 

Looking at the points it appears to be a representation of our basic map from the research stage.

What approach were you thinking of instead?

Providing a massive ArrayList of Waypoints seems sensible to me.

**Comment by SamanthaDawsonBanks** [comment]
yeah i am going to abstract it up a level so that the dummy is a DummyLiDARRead (also a MapLayer) that is used to create a "real" map rather than a hacked map object

**Comment by SamanthaDawsonBanks** [comment]
Super-seeded by #98

**Pull request closed without merging**
