### PR TITLE
Cppdatatypes5

### PR DESCRIPTION
**Pull request by SamanthaDawsonBanks**
I need to do some runtime checks but this passes the compiler > linker > builder

can someone with a bit more C++ knowledge take a look plz,

### CODE REVIEW

**Comment by SamanthaDawsonBanks** [comment]
I'm going to juggle some of the pointer around to be more invisible from the outside

**Review by stevempope — APPROVED** [review]
There are some good optimisations of the code in here and the "Unit Test" works well. Good work Dave!

**Comment by SamanthaDawsonBanks** [comment]
Addresses #112

**Review by RyanShoobert — APPROVED** [review]
The addition of the unit test ties in nicely with #88 and the code overall looks well structured. Approved.

**Pull request merged**
