### PR TITLE
Member Changes

### PR DESCRIPTION
**Pull request by stevempope**
This PR doesn't merge automatically as there is a large amount changing.

I believe this is because I didn't change to a new branch from #110 but that can be changed.

I have made several changes to the Member to prepare it for M2.

A key change is that we had way too much control of joining and leaving a Herd being left up to the member. As discussed in #94 The member wakes and a Herd is created. Merges of Herds are the only type of joining and leaving that are done. This process should be kept from interacting with the member so that we do not violate the Single responsibility rule in SOLID.

I have changed the interface to reflect the core abilities that are required.

No JUnit adjustments have been made yet, so the old ones wont pass until new ones are written. This is because the way a Member interacts with a Herd is not how I originally modelled.

I have added some security elements. The Leader of a Herd should create a Public/Private Key pair and the public key gets pushed to all members. The members should then send back an encrypted string to the leader, who sends the decrypted string back to prove that the public key is valid. Fleshing this feature out requires the same level of change on the leader side. I don't want to make such a dramatic change in a single PR.

Even if this code ends up not merged, what do people think of this direction? I believe this brings us more in line with the diagrams we have produced.

Member main creates the Herd because that way the Member constructor will have finished.

### CODE REVIEW

**Comment by stevempope** [comment]
We need to talk further about how key exchange works between member and leader.

**Review by SamanthaDawsonBanks — COMMENTED** [review]
looking at where these commits are at the code looks well formed but it will probably be a good idea to hold the merger till the corresponding Leader PR is ready?

**Review by RyanShoobert — COMMENTED** [review]
Sounds like a good plan. As a suggestion, it may be an idea to merge in what we both have (although not done) so the other has a better idea of what they are building against?

**Comment by stevempope** [comment]
Changed merge base so that this request looks at the new Merger Branch. Ryan can also put his Leader code into that branch so we can have a working leader/member before going into develop.

**Comment by stevempope** [comment]
Replaced by #113 closing.

**Pull request closed without merging**
